stepsでnodeバージョンを返す

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,5 +19,7 @@ jobs:
         with:
           node-version: '18'
 
-      - name: Force Failure
-        run: (exit 1)
+      # - name: Force Failure（強制失敗）
+        # run: (exit 1)
+      - name: Node Ver Success（成功系）
+        run: node --version
